# Generated by Django 4.2.27 on 2026-02-22 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events_document_id_fix', '0006_deletedcabinetstub'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trasheddocumentdeletedinfo',
            name='events_document_id_fix_document_id_unique',
        ),
        migrations.AlterField(
            model_name='deletedcabinetstub',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trasheddocumentdeletedinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
